use_frameworks!

platform :ios, '9.0'

target 'BaseComponents_Example' do
  pod 'BaseComponents', :path => '../'
  pod 'MJRefresh'
  target 'BaseComponents_Tests' do
    inherit! :search_paths

    
  end
end
